### ISSUE TITLE
Add a 2D toon shader

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-shaders#10]
Add a gradient-mapping shader for 2D sprites. It should support normal maps and lighting (that's provided out of the box by Godot).

**Comment by NathanLovato** [comment]
@johnnygossdev you want to take care of it?

The gist of it is creating a gradient resource and using a greyscale version of the sprite's pixels to sample the gradient - dark pixels should sample the left of the gradient, bright pixels the right side.

Here's a snippet that shows gradient sampling/mapping using the input texture.

It's a base to help you get started. I actually made a tutorial about that some time ago: https://www.youtube.com/watch?v=i7VljTl4I3w

There are different methods to convert colors to greyscale that give different results. Below is the simplest one, average, but it tends to wash out brightness.

```glsl
uniform sampler2D gradient_map : hint_black;

// ... fragment shader

vec4 color = texture(TEXTURE, UV);
float greyscale_average = (color.r + color.g + color.b) / 3.0;
float uvs = vec2(greyscale_average, 0.0);
COLOR = texture(gradient_map, uvs);
```

**Comment by johnnygossdev** [comment]
Sure! Thanks for the info! I'll get started tomorrow!

**Comment by Razoric480** [comment]
You can check out the pointilism shader. It has a luminance based greyscale function.

**Comment by johnnygossdev** [comment]
Perfect thanks!
