### ISSUE TITLE
3D water

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-shaders#12]
Create a 3D water shader.

This is a great reference: https://github.com/Platinguin/Godot-Water-Shader-Prototype

**Comment by Razoric480** [comment]
Added a water effect for more stylized games, though I'm leaving this issue open for a more oceanic effect like the one you have listed.

**Comment by NathanLovato** [comment]
I think it's good for now, it covers the elements we needed to tackle: proximity, foam, refraction...

**Comment by NathanLovato** [comment]
Thanks!
