### ISSUE TITLE
Side-view 2D water shader

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-shaders#14]
The shader is already available: see  `WaterSidescroll2DDemo`

Features:

- [x] Reflections
- [x] UV deformation affecting both reflections and water
- [x] Transition between reflection and water
- [x] Perspective deformation
- [x] Parallax mapping
- [x] Shading from parallax
- [x] Make it so the top edge isn't so sharp - displace the pixels there too
- [ ] Light support (normal maps)
- [ ] Clean up code

**Comment by JustYourAverageJosh** [comment]
Hi, thank you for this shader, it is awesome! However, I noticed that the top gets cut off abruptly. I took some code from this (also awesome) 2D water shader:
https://github.com/gamedevserj/Godot-Shaders/blob/master/WaterShader/water_shader.shader
*I  removed the foam part from his code as well for simplicity.
Now the top has a nice transition with waves. 
You may have a better way of implementing it with your shader (sorry I'm not sure how shaders work, just trial and error lol). 

I just added this to your side-view 2D water_sidescroll_2D shader code:

```
uniform float waveSmoothing =0.005;

uniform float mainWaveSpeed = 2.5;
uniform float mainWaveFrequency = 20;
uniform float mainWaveAmplitude = 0.005;

uniform float secondWaveSpeed = 2.5;
uniform float secondWaveFrequency = 20;
uniform float secondWaveAmplitude = 0.015;

uniform float thirdWaveSpeed = 2.5;
uniform float thirdWaveFrequency = 20;
uniform float thirdWaveAmplitude = 0.01;

uniform vec4 shorelineColor : hint_color = vec4(1.);
uniform float shorelineSize : hint_range(0., 0.1) = 0.005;

////////// I Inserted this part after your original shader coder

float distFromTop = mainWaveAmplitude * sin(UV.x * mainWaveFrequency + TIME * mainWaveSpeed) + mainWaveAmplitude
	 			+ secondWaveAmplitude * sin(UV.x * secondWaveFrequency + TIME * secondWaveSpeed) + secondWaveAmplitude
				+ thirdWaveAmplitude * cos(UV.x * thirdWaveFrequency - TIME * thirdWaveSpeed) + thirdWaveAmplitude;
	
	float waveArea = UV.y - distFromTop;
	
	float shoreline = smoothstep(0.0, waveArea, shorelineSize); 
	COLOR.rgb += shoreline * shorelineColor.rgb;
	
	float upperPart = 1.0 - step(0.0, waveArea); 
	waveArea = smoothstep(waveArea, 0., waveSmoothing * (1.-UV.y));
	waveArea -= upperPart;
	COLOR.a *= waveArea;
```
And here is an image of the result! I am very happy with it, just thought I'd let you know, if you wanted to implement something like it to your shader as well! 

![2d_water_with_waves](https://user-images.githubusercontent.com/47060866/87086824-18cb8100-c200-11ea-88bc-851d2863fbe8.png)

**Comment by NathanLovato** [comment]
I think for this shader, we can do something simpler: displace the top edge of the water based on the parallax, maybe add a bit of that fresnel effect. As it has some perspective, the sine at the top makes it look a bit strange, as it now looks both seen in a side orthographic view at the top and seen in perspective below the top edge.

**Comment by NathanLovato** [comment]
But thanks for taking the time to do that! I'll add a note to the top post with the task list.

**Comment by NathanLovato** [comment]
Done since a few days ago, the water also has a shoreline now.
