### ISSUE TITLE
Unify the look of 3D scenes

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-shaders#2]
The 3D scenes are lacking some coherent and quality world environment. As for the 2D scenes (#1 ) we could have a base 3D demo scene they all inherit (or a template with reusable components).

**Comment by Razoric480** [comment]
3D scenes have been refactored to have a common ancestor in res://Common/Demo3DBase.tscn. Though at the moment there is no unification of how they look, just how they function. Wasn't sure what changes you were after in particular, but now it should be easier than not to do it.

**Comment by NathanLovato** [comment]
Mainly I'd say having the same base worldenvironment, sharing some materials maybe, and maybe having a default light setup so we don't have to redo it by hand every time.

**Comment by Razoric480** [comment]
Okay. I'll import in ImpossibleCube's stuff, as it's the most mature one, I think.

**Comment by Razoric480** [comment]
Okay, that's done and pushed. I merged in the sun, the ground and the world environment from impossible cube, now all the scenes use it.

Anything else you'd like to do, feel free until you feel we can close this issue.

**Comment by NathanLovato** [comment]
Looking good!
