### ISSUE TITLE
Add a text description in the demos

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-shaders#3]
What the shaders do and how they work isn't always self-explanatory, especially as some are there for learning purposes or are low-cost variants of more expensive real-time effects, like the pre-baked glow.

We could use a UI component that gives some info about the shaders, available in all demo scenes. It can be part of a base scene that all demos inherit, or exist as a reusable component. See #1 and #2

**Comment by Razoric480** [comment]
I've added first pass for the 2D demos. Will refactor the 3D scenes next.

I went with the re-usable component scene route.

**Comment by NathanLovato** [comment]
Perfect, thanks!
