### ISSUE TITLE
ShockwaveDemo: mask does not update with the shockwave

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-shaders#4]
The Mask node, that displays a black-and-white, 2D representation of the shockwave's height-map, does not animate with the actual shockwave.

This is because it doesn't use the same material as the shockwave. But using the same material doesn't work either. It gives me a pure white rectangle.

**Comment by Razoric480** [comment]
The black and white mask representation is there just to show what the mask looks like with the current settings and at a "normal" radius, rather than how the mask is currently looking in the back buffer. But I can make it animate, sure.

**Comment by NathanLovato** [comment]
Ah I see! If that's not too much of a bother, I think it'd be beneficial. In particular, I wanted to improve the effect, make the wave lose energy as it expands, and it's difficult without seeing the mask animate.
