### ISSUE TITLE
Improve background of 2D demos

### ISSUE THREAD

**Issue by Razoric480** [GDQuest/godot-shaders#5]
A temporary background was added as in #1 , just to make sure it worked. The actual sprucing up with a _nice_ background can now occur.

Making them inherit from a common ancestor might be a bit trickier, though. Often times, the background is part of the 'main scene view' rather than the demo.

**Comment by NathanLovato** [comment]
Yeah, that's the problem. I was actually working on it, but need the demos to be transparent for it to work. I don't want us to have to maintain background nodes in every scene.

**Comment by Razoric480** [comment]
I've started refactoring the scenes to enable it.

**Comment by NathanLovato** [comment]
Thanks, great! I'll take care of the background after that if you don't mind.

**Comment by Razoric480** [comment]
All 2D demos now have an inherited scene that's in res://Common/BaseDemo2D.tscn . Right now it's just a TextureRect with a throwaway gradients, so not much to it, but they all display it just fine.

Except for the BlurViewportContainers and BlurViewportTextures demos, as they use their own background already.
