### ISSUE TITLE
Outline2DDemo: Make the outline appear on mouse hover?

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-shaders#7]
The demo uses an animated cursor that goes over the characters. Area2D should be able to detect mouse hover from the user so I'd like to suggest we use that kind of user interaction when we can, to make the demos more interactive.

**Comment by Razoric480** [comment]
Yeah, I went with an animated cursor for the purpose of making the preview videos. Changing them to a cursor is certainly open.

**Comment by NathanLovato** [comment]
I tried and couldn't get the Collision2D (Area2Ds) to react to mouse hover. Will have to try it again.

**Comment by Razoric480** [comment]
Both the Outline2DDemo control and the TextureRect inside of the Background scene need to have their mouse filter set to Ignore.

**Comment by NathanLovato** [comment]
AH!

Thanks :)

**Comment by NathanLovato** [comment]
Done with 47da4f103a51ad451f5760bfcc2b210460618084
